[package]
name = "artcode"
version = "0.1.0"
authors = ["Grayson <me@russellhay.com>"]
edition = "2018"
license = "MIT"
description = "Converts dates into artcode coordinates"
repository = "https://github.com/RussTheAerialist/artcode"

[dependencies]
clap = "2.33.0"
chrono = "0.4.10"
